### ISSUE TITLE
Use default os image location if not found in user's project

### ISSUE THREAD

**Issue by tahsinrahman** [kubernetes-sigs/cluster-api-provider-gcp#176] opened 2019-09-24 03:59 UTC
/kind feature

**Describe the solution you'd like**

Currently, CAPG expects os image should be present in my gcp project
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/4591af53eb02bb17fd08d22999bf7b7534fabab9/cloud/services/compute/instances.go#L91-L93

In CAPA, if we don't define AMI, it looks for image in  heptio org

I'd be great if we have similar thing here, so user trying out CAPG don't have to build and push their own images into their project

**Comment by vincepri** [comment] 2019-09-24 14:52
Seems like a duplicate of #152

**Closed** 2020-02-21 16:25 UTC
Labels: kind/feature, lifecycle/rotten
