### ISSUE TITLE
If minikube already exists then create cluster doesn't work

### ISSUE THREAD

**Issue by bsingarayan** [kubernetes-sigs/cluster-api-provider-gcp#87] opened 2019-01-04 19:12 UTC
./bin/clusterctl create cluster --provider google -c cmd/clusterctl/examples/google/out/cluster.yaml -m cmd/clusterctl/examples/google/out/machines.yaml -p cmd/clusterctl/examples/google/out/provider-components.yaml -a cmd/clusterctl/examples/google/out/addons.yaml --minikube="kubernetes-version=v1.12.4" --v=4
I0104 11:07:43.406268   28287 machineactuator.go:813] Using the default GCP client
I0104 11:07:43.408657   28287 plugins.go:39] Registered cluster provisioner "google"
I0104 11:07:43.412794   28287 createbootstrapcluster.go:28] Creating bootstrap cluster
I0104 11:07:43.412829   28287 minikube.go:58] Running: minikube [start --bootstrapper=kubeadm --kubernetes-version=v1.12.4]
I0104 11:08:36.802657   28287 minikube.go:62] Ran: minikube [start --bootstrapper=kubeadm --kubernetes-version=v1.12.4] Output: Starting local Kubernetes v1.12.4 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Machine exists, restarting cluster components...
Verifying kubelet health ...
Verifying apiserver health ....Kubectl is now configured to use the cluster.
Loading cached images from config file.

Everything looks great. Please enjoy minikube!
I0104 11:08:36.806728   28287 clusterdeployer.go:95] Applying Cluster API stack to bootstrap cluster
I0104 11:08:36.806756   28287 applyclusterapicomponents.go:27] Applying Cluster API Provider Components
I0104 11:08:36.806776   28287 clusterclient.go:521] Waiting for kubectl apply...
I0104 11:08:37.436939   28287 clusterclient.go:550] Waiting for Cluster v1alpha resources to become available...
I0104 11:08:37.447889   28287 clusterclient.go:563] Waiting for Cluster v1alpha resources to be listable...
I0104 11:08:37.461941   28287 clusterdeployer.go:100] Provisioning target cluster via bootstrap cluster
I0104 11:08:41.478073   28287 applycluster.go:37] Creating cluster object test1-jtpdx in namespace "default"
I0104 11:08:45.488807   28287 createbootstrapcluster.go:37] Cleaning up bootstrap cluster.
I0104 11:08:45.488838   28287 minikube.go:58] Running: minikube [delete]
I0104 11:08:46.652070   28287 minikube.go:62] Ran: minikube [delete] Output: Deleting local Kubernetes cluster...
Machine deleted.
F0104 11:08:46.652839   28287 create_cluster.go:64] unable to create cluster "test1-jtpdx" in bootstrap cluster: error creating cluster in namespace default: clusters.cluster.k8s.io "test1-jtpdx" already exists

**Comment by roberthbailey** [comment] 2019-01-11 19:11
@bsingarayan - what do you think clusterctl should do in this case? Should it fail fast if minikube exists? One option is to pass in the `--existing-bootstrap-cluster-kubeconfig` flag pointing at the kubeconfig file for minikube to use a running minikube instead of trying to create minikube.

**Comment by roberthbailey** [comment] 2019-01-11 20:10
This is an issue with clusterctl "upstream", and is tracked in https://github.com/kubernetes-sigs/cluster-api/issues/413 so I'm going to close this as a dupe of that one.

**Closed by roberthbailey** 2019-01-11 20:10 UTC
Labels: kind/bug, priority/important-soon
